version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: workspace-booking
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: workspace_booking
      JWT_KEY: ${JWT_KEY}
      PORT: ${PORT}
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: workspace_booking
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
