openapi: "3.0.4"
info:
  version: 1.0.0
  title: Workspace Booking
paths:
  /offices:
    $ref: ./resources/offices/offices.yaml
  /offices/{id}:
    $ref: ./resources/offices/office.yaml
  /offices/{officeId}/employeeGroups/{employeeGroupId}:
    $ref: ./resources/offices/officeEmployeeGroup.yaml
  /rooms:
    $ref: ./resources/rooms/rooms.yaml
  /rooms/{id}:
    $ref: ./resources/rooms/room.yaml
  /rooms/{id}/layout:
    $ref: ./resources/rooms/layout.yaml
  /rooms/{id}/bookings:
    $ref: ./resources/rooms/bookings.yaml
  /employeeGroups:
    $ref: ./resources/employeeGroups/employeeGroups.yaml
  /employeeGroups/{id}:
    $ref: ./resources/employeeGroups/employeeGroup.yaml
  /workplaces:
    $ref: ./resources/workplaces/workplaces.yaml
  /workplaces/{id}:
    $ref: ./resources/workplaces/workplace.yaml
  /meetingRooms:
    $ref: ./resources/meetingRooms/meetingRooms.yaml
  /meetingRooms/{id}:
    $ref: ./resources/meetingRooms/meetingRoom.yaml
  /employees:
    $ref: ./resources/employees/employees.yaml
  /employees/{id}:
    $ref: ./resources/employees/employee.yaml
  /employees/{id}/grant-admin:
    $ref: ./resources/employees/employeeGrantAdmin.yaml
  /workplaceBookings:
    $ref: ./resources/workplaces/bookings/workplaceBookings.yaml
  /workplaceBookings/{id}:
    $ref: ./resources/workplaces/bookings/workplaceBooking.yaml
  /meetingRoomBookings:
    $ref: ./resources/meetingRooms/bookings/meetingRoomBookings.yaml
  /meetingRoomBookings/{id}:
    $ref: ./resources/meetingRooms/bookings/meetingRoomBooking.yaml
  /occupancy/offices/{id}:
    $ref: ./resources/occupancy/offices/office.yaml
  /occupancy/rooms:
    $ref: ./resources/occupancy/rooms/rooms.yaml
  /occupancy/rooms/{id}:
    $ref: ./resources/occupancy/rooms/room.yaml
  /imports:
    $ref: ./resources/rooms/imports/import.yaml
security:
  - bearerTokenAuth: []
components:
  securitySchemes:
    bearerTokenAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
