openapi: "3.0.4"
info:
  version: 1.0.0
  title: Workplace Booking
paths:
  /offices:
    $ref: ./resources/offices/offices.yaml
  /offices/{id}:
    $ref: ./resources/offices/office.yaml
  /rooms:
    $ref: ./resources/rooms/rooms.yaml
  /rooms/{id}:
    $ref: ./resources/rooms/room.yaml
